// <auto-generated />
using System;
using FormExample.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FormExample.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FormExample.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patient");
                });

            modelBuilder.Entity("FormExample.Models.PrimaryFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PatientId")
                        .HasColumnType("int");

                    b.Property<int?>("PrimaryFindingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PrimaryFindingId");

                    b.ToTable("PrimaryFinding");
                });

            modelBuilder.Entity("FormExample.Models.SecondaryFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryFindingId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryFindingId");

                    b.ToTable("SecondaryFinding");
                });

            modelBuilder.Entity("FormExample.Models.PrimaryFinding", b =>
                {
                    b.HasOne("FormExample.Models.Patient", null)
                        .WithMany("PrimaryFindings")
                        .HasForeignKey("PatientId");

                    b.HasOne("FormExample.Models.PrimaryFinding", null)
                        .WithMany("PrimaryFindings")
                        .HasForeignKey("PrimaryFindingId");
                });

            modelBuilder.Entity("FormExample.Models.SecondaryFinding", b =>
                {
                    b.HasOne("FormExample.Models.PrimaryFinding", "PrimaryFinding")
                        .WithMany()
                        .HasForeignKey("PrimaryFindingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
